apiVersion: v1
kind: Service
metadata:
  labels:
    name: scs-service-bus
  name: scs-service-bus
spec:
  type: ClusterIP
  selector:
    app: scs-service-bus
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP